- name: Upgrade ubuntu
  hosts: ubuntu
  gather_facts: true
  become: true

  roles:
    - bootstrap
    - update_package_cache
    - update

- name: Upgrade RPi
  hosts: pi
  gather_facts: min
  become: true

  roles:
    - rpi_upgrade

- name: Upgrade containers
  hosts: compose
  gather_facts: true
  become: true

  roles:
    - docker_compose
